### ISSUE TITLE
Issue with pacman files database

### ISSUE THREAD

**Issue by krathalan** [anatol/pacoloco#44]
Pacoloco crashed after I tried to search for which package had a specific binary. The specific command I used was:

`sudo pacman -Fy /usr/bin/host`

The log of Pacoloco is as follows:

```
Jan 10 19:14:20 alpha systemd[1]: Started Pacoloco caching proxy server.
Jan 10 19:14:20 alpha pacoloco[2173366]: pacoloco.go:102: Reading config file from /etc/pacoloco.yaml
Jan 10 19:14:20 alpha pacoloco[2173366]: prefetch.go:34: The prefetching routine will be run on 2022-01-11 03:00:00.000036132 -0800 PST m=+27939.112777436
Jan 10 19:14:20 alpha pacoloco[2173366]: prefetch_db.go:78: Creating /var/cache/pacoloco/sqlite-pkg-cache.db
Jan 10 19:14:20 alpha pacoloco[2173366]: pacoloco.go:129: Starting server at port 9129
Jan 10 19:16:30 alpha pacoloco[2173366]: pacoloco.go:446: downloading https://arch.mirror.constant.com//community/os/x86_64/community.db
Jan 10 19:16:30 alpha pacoloco[2173366]: pacoloco.go:446: downloading https://arch.mirror.constant.com//extra/os/x86_64/extra.db
Jan 10 19:16:30 alpha pacoloco[2173366]: pacoloco.go:446: downloading https://arch.mirror.constant.com//core/os/x86_64/core.db
Jan 10 19:17:26 alpha pacoloco[2173366]: pacoloco.go:138: open /var/cache/pacoloco/pkgs/archlinux/extra.db.sig: no such file or directory
Jan 10 19:17:26 alpha pacoloco[2173366]: pacoloco.go:138: open /var/cache/pacoloco/pkgs/archlinux/community.db.sig: no such file or directory
Jan 10 19:17:26 alpha pacoloco[2173366]: pacoloco.go:138: open /var/cache/pacoloco/pkgs/archlinux/core.db.sig: no such file or directory
Jan 10 19:54:04 alpha pacoloco[2173366]: pacoloco.go:446: downloading https://arch.mirror.constant.com//extra/os/x86_64/extra.files
Jan 10 19:54:04 alpha pacoloco[2173366]: pacoloco.go:446: downloading https://arch.mirror.constant.com//core/os/x86_64/core.files
Jan 10 19:54:04 alpha pacoloco[2173366]: pacoloco.go:446: downloading https://arch.mirror.constant.com//community/os/x86_64/community.files
Jan 10 19:54:04 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'core.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:05 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'extra.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:05 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'community.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:22 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'extra.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:22 alpha pacoloco[2173366]: pacoloco.go:486: serving cached file /var/cache/pacoloco/pkgs/archlinux/extra.files
Jan 10 19:54:22 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'extra.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:22 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'community.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:22 alpha pacoloco[2173366]: pacoloco.go:486: serving cached file /var/cache/pacoloco/pkgs/archlinux/community.files
Jan 10 19:54:22 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'community.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:22 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'core.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:22 alpha pacoloco[2173366]: pacoloco.go:486: serving cached file /var/cache/pacoloco/pkgs/archlinux/core.files
Jan 10 19:54:22 alpha pacoloco[2173366]: prefetch.go:78: error: package with name 'core.files' cannot be prefetched cause it doesn't follow the package name formatting regex
Jan 10 19:54:40 alpha pacoloco[2173366]: fatal error: concurrent map writes
Jan 10 19:54:40 alpha pacoloco[2173366]: goroutine 1197 [running]:
Jan 10 19:54:40 alpha pacoloco[2173366]: runtime.throw({0x562fa2341285, 0x562fa1f6b3d4})
Jan 10 19:54:40 alpha pacoloco[2173366]:         runtime/panic.go:1198 +0x71 fp=0xc00004d620 sp=0xc00004d5f0 pc=0x562fa1ee5d51
Jan 10 19:54:40 alpha pacoloco[2173366]: runtime.mapassign_faststr(0x562fa2441100, 0xc0001f8ae0, {0xc0000287f8, 0x18})
...
```

Full log here: https://gist.github.com/krathalan/e1147dd4ab036f63847e2a9363843280

**Comment by anatol** [comment]
cc @Focshole

**Comment by Focshole** [comment]
As first, thank you for reporting, your logs have been very useful.
I had found an issue unrelated to the crash and I have to further investigate the one that caused the crash.
- The first issue is in the prefetching part, which throws an error (it does no harm but there is no point in showing it), saying that it cannot prefetch `whatever.files`. This is an expected behaviour, but it shouldn't try to add them to the db too.
- The crash issue is due to a race condition which it may have been triggered on a map, I'll have to further investigate on that. I'd guess that it is on `lastModificationTime` and `lastMirrorlistCheck` maps
The fix should be something like [this](https://stackoverflow.com/questions/45585589/golang-fatal-error-concurrent-map-read-and-map-write/45585833)

**Comment by Focshole** [comment]
I'll work on this fix probably the next month, starting from checking all the shared resources between threads.
